#!/bin/bash

# run with -d for debug symbols

# Exit on any error
set -e

# Parse command line arguments
DEBUG_MODE=OFF
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -d|--debug) DEBUG_MODE=ON ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

EMCC_DEBUG=1

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR="$SCRIPT_DIR/build"
WEB_DIR="$SCRIPT_DIR/web"

echo "Script dir: $SCRIPT_DIR"
echo "Build dir: $BUILD_DIR"
echo "Web dir: $WEB_DIR"
echo "Debug mode: $DEBUG_MODE"

mkdir -p "$BUILD_DIR"
mkdir -p "$WEB_DIR"

cd "$BUILD_DIR"

echo "Running CMake..."
emcmake cmake -DCMAKE_BUILD_TYPE=$([ "$DEBUG_MODE" == "ON" ] && echo "Debug" || echo "Release") -DDEBUG_MODE=$DEBUG_MODE -S "$SCRIPT_DIR" -B "$BUILD_DIR"

# Check if Makefile was generated
if [ ! -f "Makefile" ]; then
    echo "Error: Makefile was not generated by CMake in $BUILD_DIR"
    exit 1
fi

echo "Running emmake make..."
emmake make

if [ ! -f "mshv_ft8.js" ] || [ ! -f "mshv_ft8.wasm" ]; then
    echo "Error: Output files were not generated in $BUILD_DIR"
    exit 1
fi

# Copy the output to the web directory
cp mshv_ft8.js mshv_ft8.wasm "$WEB_DIR/"

echo "Build complete. Output files are in $WEB_DIR"