#!/bin/bash

# Exit on any error
set -e

# Directory setup
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR="$SCRIPT_DIR/build"
WEB_DIR="$SCRIPT_DIR/web"

echo "Script dir: $SCRIPT_DIR"
echo "Build dir: $BUILD_DIR"
echo "Web dir: $WEB_DIR"

# Create build directory if it doesn't exist
mkdir -p "$BUILD_DIR"

# Create web directory if it doesn't exist
mkdir -p "$WEB_DIR"

# Navigate to build directory
cd "$BUILD_DIR"

echo "Running CMake..."
emcmake cmake -DCMAKE_BUILD_TYPE=Release -S "$SCRIPT_DIR" -B "$BUILD_DIR"

# Check if Makefile was generated
if [ ! -f "Makefile" ]; then
    echo "Error: Makefile was not generated by CMake in $BUILD_DIR"
    exit 1
fi

echo "Contents of $BUILD_DIR after running CMake:"
ls -la "$BUILD_DIR"

echo "Running emmake make..."
emmake make

# Check if output files were generated
if [ ! -f "mshv_ft8.js" ] || [ ! -f "mshv_ft8.wasm" ]; then
    echo "Error: Output files were not generated in $BUILD_DIR"
    exit 1
fi

# Copy the output to the web directory
cp mshv_ft8.js mshv_ft8.wasm "$WEB_DIR/"

echo "Build complete. Output files are in $WEB_DIR"